### ISSUE TITLE
Null values found in pull

### ISSUE THREAD

**Issue by Steampunkrue** [massmep/env#25]
Files affected:
`pull.go:101`
`retrieve.go:92`

In both cases, a null value was provided where no null value should be. Both errors vanished when re-running the same command. Should look into reply data, ensure proper data is being returned from salesforce, and properly parsed into `structs`.

**Comment by Steampunkrue** [comment]
Crash log from `pull` command 

```bash

SeanH@work ~/D/S/P/Spring16> dev pull spring16
Queued

Status:
Pending

Retrieve failed!

Files pulled:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8d579]

goroutine 1 [running]:
github.com/Steampunkrue/env/dev/cmd.writePulledFiles(0x0, 0x0, 0x0, 0x69a028, 0xc820010c90)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/cmd/pull.go:101 +0xd19
github.com/Steampunkrue/env/dev/cmd.pullRun(0xc82000a200, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/cmd/pull.go:77 +0x45f
github.com/Steampunkrue/env/dev/lib.CommandData.Run(0x3c1bb8, 0x4, 0x43f960, 0x32, 0x470450, 0xc82000a200, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/lib/command.go:39 +0x48
github.com/Steampunkrue/env/dev/lib.(*CommandData).Run(0xc82000af30, 0xc82000a200, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc5
main.internalMain(0xc82000a1e0, 0x3, 0x3)
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:35 +0x2e1
main.main()
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:20 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

```
