### ISSUE TITLE
Pull failed with runtime error 

### ISSUE THREAD

**Issue by Steampunkrue** [massmep/env#33]
```
SeanH@work ~/D/S/P/VSM> dev pull VSM
Queued

Status:
Pending

Retrieve failed!

Files pulled:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8d579]

goroutine 1 [running]:
github.com/Steampunkrue/env/dev/cmd.writePulledFiles(0x0, 0x0, 0x0, 0x69a028, 0xc820012c90)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/cmd/pull.go:101 +0xd19
github.com/Steampunkrue/env/dev/cmd.pullRun(0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/cmd/pull.go:77 +0x45f
github.com/Steampunkrue/env/dev/lib.CommandData.Run(0x3c1bb8, 0x4, 0x43f960, 0x32, 0x470450, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/lib/command.go:39 +0x48
github.com/Steampunkrue/env/dev/lib.(*CommandData).Run(0xc82000afc0, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc5
main.internalMain(0xc82000a240, 0x3, 0x3)
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:35 +0x2e1
main.main()
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:20 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by Steampunkrue** [comment]
Failed to occur on second `pull`.

**Comment by Steampunkrue** [comment]
```
SeanH@work ~/D/S/P/VSM> dev deploy VSM 
Queued

InProgress

Failures:
components/CityLookup.component
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7c922]

goroutine 1 [running]:
github.com/Steampunkrue/env/dev/lib.CheckAsyncDeploy(0xc8203483c0, 0x12, 0xc8200107c0, 0x15, 0xc820013050, 0xc, 0xc820010900, 0x19, 0xc8202d0bd0, 0x70, ...)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/lib/deploy.go:76 +0xc92
github.com/Steampunkrue/env/dev/cmd.deployRun(0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/cmd/deploy.go:73 +0x44d
github.com/Steampunkrue/env/dev/lib.CommandData.Run(0x3c0628, 0x6, 0x44bc60, 0x42, 0x470430, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/lib/command.go:39 +0x48
github.com/Steampunkrue/env/dev/lib.(*CommandData).Run(0xc82000af60, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc5
main.internalMain(0xc82000a240, 0x3, 0x3)
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:35 +0x2e1
main.main()
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:20 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by Steampunkrue** [comment]
Failures:
components/CityLookup.component
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7c922]

goroutine 1 [running]:
github.com/Steampunkrue/env/dev/lib.CheckAsyncDeploy(0xc82032e360, 0x12, 0xc8200107c0, 0x15, 0xc820013050, 0xc, 0xc820010900, 0x19, 0xc820061f10, 0x70, ...)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/lib/deploy.go:76 +0xc92
github.com/Steampunkrue/env/dev/cmd.deployRun(0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/cmd/deploy.go:73 +0x44d
github.com/Steampunkrue/env/dev/lib.CommandData.Run(0x3c0628, 0x6, 0x44bc60, 0x42, 0x470430, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/Seanh/go/src/github.com/Steampunkrue/env/dev/lib/command.go:39 +0x48
github.com/Steampunkrue/env/dev/lib.(*CommandData).Run(0xc82000af60, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc5
main.internalMain(0xc82000a240, 0x3, 0x3)
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:35 +0x2e1
main.main()
	/Users/SeanH/go/src/github.com/Steampunkrue/env/dev/main.go:20 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

**Comment by Steampunkrue** [comment]
Seems to be a result of a compile error in the deployed component.
